---
- name: Install go lang and tools
  include_role:
    name: fubarhouse.golang

- name: Get go binaries to copy
  find:
    paths: "{{ GOPATH + '/bin' }}"
    file_type: file
  register: copy_files
  when: go_get is defined

- name: Copy Go binaries to /usr/local/bin
  copy:
    src: "{{ item.path }}"
    dest: "/usr/local/bin"
    remote_src: true
    mode: 0755
  loop: "{{ copy_files.files }}"
  when: copy_files is defined
